server.port=8092
spring.application.name=cuentas-service
spring.config.import=optional:configserver:http://localhost:8888
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

app.security.user=admin
app.security.password=admin123