spring.application.name=bank-batch

spring.datasource.url=jdbc:postgresql://localhost:5433/banco
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

spring.batch.jdbc.initialize-schema=never
spring.batch.job.enabled=false

# ---------------------------------------------
# HTTPS
# ---------------------------------------------
server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:bank-batch.p12
server.ssl.key-store-password=changeit
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=bank-batch