server.port=8091
spring.application.name=clientes-service
spring.config.import=optional:configserver:http://localhost:8888
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# credenciales básicas para el paso de seguridad
app.security.user=admin
app.security.password=admin123